server:
  port: 8085

spring:
  name: backenddevchallenge



logging:
  level:
    org:
      springframework.web: "trace"
      apache.hc.client5.http: "trace"
    com.limepay.backenddevchallenge: "debug"
