server:
  port: 8085

spring:
  name: backenddevchallenge

limepay:
  movies.url: "https://wiremock.dev.eroninternational.com/api/movies/search?page={page}"
  cache.expiry: 60 #in minutes

logging:
  level:
    org:
      springframework.web: "trace"
      apache.hc.client5.http: "trace"
    com.limepay.backenddevchallenge: "debug"
